#! /bin/sh

set -e

##DEBHELPER##

if [ -x /usr/bin/update-mime-database ]; then
    update-mime-database /usr/share/mime
fi

if [ -x /usr/bin/update-desktop-database ]; then
    update-desktop-database /usr/share/applications
fi

if [ -x /usr/bin/hildon-update-category-database ]; then
    hildon-update-category-database /usr/share/mime
fi
